String cron_string = BRANCH_NAME == "master" ? "@daily" : ""
properties([
  pipelineTriggers([
    [
      $class: 'BitBucketPPRTrigger',
      triggers : [
        [
          $class: 'BitBucketPPRPullRequestTriggerFilter',
          actionFilter: [
            $class: 'BitBucketPPRPullRequestCreatedActionFilter',
          ]
        ],
        [
          $class: 'BitBucketPPRPullRequestTriggerFilter',
          actionFilter: [
            $class: 'BitBucketPPRPullRequestMergedActionFilter',
          ]
        ],
        [
          $class: 'BitBucketPPRRepositoryTriggerFilter',
          actionFilter: [
            $class: 'BitBucketPPRRepositoryPushActionFilter',
            triggerAlsoIfNothingChanged: true,
            triggerAlsoIfTagPush: false,
            allowedBranches: ""
          ]
        ]
      ]
    ]
  ])
])

pipeline {
    agent { 
        dockerfile {filename "devops/Dockerfile"}
    }

    triggers {
        cron(cron_string)    
    }

    options { disableConcurrentBuilds() }
    stages {

        stage ('Build') {

            steps {
                bitbucketStatusNotify(buildState: 'INPROGRESS')
                sh 'python3 -u devops/entrypoint.py'
            }
        }
        stage ('Tests') {

            steps {
                bitbucketStatusNotify(buildState: 'TESTING')

                dir ('releasebuild') {
                    sh 'ctest'
                }   
            }
        }
        stage ('Pack') {
            steps {
                dir ('releasebuild') {
                    sh 'cpack -G TGZ'
                }   
            }
        }
    }

    post {
        cleanup { script:  cleanWs() }
        always  { 
                  chuckNorris() 
                  }
        success { 
                  bitbucketStatusNotify(buildState: 'SUCCESSFUL')
                  archiveArtifacts '**/SDKLibraries*, **/release-notes.txt'
                  }
        failure {
                  bitbucketStatusNotify(buildState: 'FAILED')
        script: emailext (
                subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                <p>Check console output (account needed) at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
                recipientProviders: [[$class: 'CulpritsRecipientProvider'],
                [$class: 'DevelopersRecipientProvider'],
                [$class: 'RequesterRecipientProvider'], 
                [$class: 'FailingTestSuspectsRecipientProvider'],
                [$class: 'FirstFailingBuildSuspectsRecipientProvider'],
                [$class: 'UpstreamComitterRecipientProvider']]
                )
        }
    }
}

