# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ts_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ts_messages.proto',
  package='ts_messaging',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11ts_messages.proto\x12\x0cts_messaging\"\x1f\n\x0fRegisterRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\" \n\rRegisterReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"8\n\x12\x43reateGroupRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\t\n\x01m\x18\x02 \x01(\x05\x12\t\n\x01n\x18\x03 \x01(\x05\"#\n\x10\x43reateGroupReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\rInviteRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\t\"2\n\x0bInviteReply\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x12\n\nacceptance\x18\x02 \x01(\x08\x32\xf8\x01\n\tTSService\x12L\n\x0c\x43\x61llRegister\x12\x1d.ts_messaging.RegisterRequest\x1a\x1b.ts_messaging.RegisterReply\"\x00\x12U\n\x0f\x43\x61llCreateGroup\x12 .ts_messaging.CreateGroupRequest\x1a\x1e.ts_messaging.CreateGroupReply\"\x00\x12\x46\n\nCallInvite\x12\x1b.ts_messaging.InviteRequest\x1a\x19.ts_messaging.InviteReply\"\x00\x62\x06proto3')
)




_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='ts_messaging.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='ts_messaging.RegisterRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=66,
)


_REGISTERREPLY = _descriptor.Descriptor(
  name='RegisterReply',
  full_name='ts_messaging.RegisterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ts_messaging.RegisterReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=100,
)


_CREATEGROUPREQUEST = _descriptor.Descriptor(
  name='CreateGroupRequest',
  full_name='ts_messaging.CreateGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='ts_messaging.CreateGroupRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m', full_name='ts_messaging.CreateGroupRequest.m', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n', full_name='ts_messaging.CreateGroupRequest.n', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=158,
)


_CREATEGROUPREPLY = _descriptor.Descriptor(
  name='CreateGroupReply',
  full_name='ts_messaging.CreateGroupReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ts_messaging.CreateGroupReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=195,
)


_INVITEREQUEST = _descriptor.Descriptor(
  name='InviteRequest',
  full_name='ts_messaging.InviteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupId', full_name='ts_messaging.InviteRequest.groupId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=229,
)


_INVITEREPLY = _descriptor.Descriptor(
  name='InviteReply',
  full_name='ts_messaging.InviteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupId', full_name='ts_messaging.InviteReply.groupId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceptance', full_name='ts_messaging.InviteReply.acceptance', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=281,
)

DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterReply'] = _REGISTERREPLY
DESCRIPTOR.message_types_by_name['CreateGroupRequest'] = _CREATEGROUPREQUEST
DESCRIPTOR.message_types_by_name['CreateGroupReply'] = _CREATEGROUPREPLY
DESCRIPTOR.message_types_by_name['InviteRequest'] = _INVITEREQUEST
DESCRIPTOR.message_types_by_name['InviteReply'] = _INVITEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'ts_messages_pb2'
  # @@protoc_insertion_point(class_scope:ts_messaging.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterReply = _reflection.GeneratedProtocolMessageType('RegisterReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREPLY,
  '__module__' : 'ts_messages_pb2'
  # @@protoc_insertion_point(class_scope:ts_messaging.RegisterReply)
  })
_sym_db.RegisterMessage(RegisterReply)

CreateGroupRequest = _reflection.GeneratedProtocolMessageType('CreateGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGROUPREQUEST,
  '__module__' : 'ts_messages_pb2'
  # @@protoc_insertion_point(class_scope:ts_messaging.CreateGroupRequest)
  })
_sym_db.RegisterMessage(CreateGroupRequest)

CreateGroupReply = _reflection.GeneratedProtocolMessageType('CreateGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGROUPREPLY,
  '__module__' : 'ts_messages_pb2'
  # @@protoc_insertion_point(class_scope:ts_messaging.CreateGroupReply)
  })
_sym_db.RegisterMessage(CreateGroupReply)

InviteRequest = _reflection.GeneratedProtocolMessageType('InviteRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVITEREQUEST,
  '__module__' : 'ts_messages_pb2'
  # @@protoc_insertion_point(class_scope:ts_messaging.InviteRequest)
  })
_sym_db.RegisterMessage(InviteRequest)

InviteReply = _reflection.GeneratedProtocolMessageType('InviteReply', (_message.Message,), {
  'DESCRIPTOR' : _INVITEREPLY,
  '__module__' : 'ts_messages_pb2'
  # @@protoc_insertion_point(class_scope:ts_messaging.InviteReply)
  })
_sym_db.RegisterMessage(InviteReply)



_TSSERVICE = _descriptor.ServiceDescriptor(
  name='TSService',
  full_name='ts_messaging.TSService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=284,
  serialized_end=532,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallRegister',
    full_name='ts_messaging.TSService.CallRegister',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CallCreateGroup',
    full_name='ts_messaging.TSService.CallCreateGroup',
    index=1,
    containing_service=None,
    input_type=_CREATEGROUPREQUEST,
    output_type=_CREATEGROUPREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CallInvite',
    full_name='ts_messaging.TSService.CallInvite',
    index=2,
    containing_service=None,
    input_type=_INVITEREQUEST,
    output_type=_INVITEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TSSERVICE)

DESCRIPTOR.services_by_name['TSService'] = _TSSERVICE

# @@protoc_insertion_point(module_scope)
