gnome-terminal -- python3 client.py Murphy
gnome-terminal -- python3 client.py Boris
gnome-terminal -- python3 client.py Bergen
gnome-terminal -- python3 client.py Lottie
gnome-terminal -- python3 client.py Greta
#gnome-terminal -- python3 client.py Chandra
#gnome-terminal -- python3 client.py Simon
#gnome-terminal -- python3 client.py Ferdia
#gnome-terminal -- python3 client.py Archie
#gnome-terminal -- python3 client.py Anja
