gnome-terminal -- python3 client_twisted.py Murphy
gnome-terminal -- python3 client_twisted.py Boris
gnome-terminal -- python3 client_twisted.py Bergen
gnome-terminal -- python3 client_twisted.py Lottie
gnome-terminal -- python3 client_twisted.py Greta
#gnome-terminal -- python3 client_twisted.py Chandra
#gnome-terminal -- python3 client_twisted.py Simon
#gnome-terminal -- python3 client_twisted.py Ferdia
#gnome-terminal -- python3 client_twisted.py Archie
#gnome-terminal -- python3 client_twisted.py Anja
