# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ts_enums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ts_enums.proto',
  package='ts_messaging',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ets_enums.proto\x12\x0cts_messaging*7\n\x08\x43\x61lcType\x12\x13\n\x0fPRIVATEKEYSHARE\x10\x00\x12\x0b\n\x07LITTLEK\x10\x01\x12\t\n\x05\x41LPHA\x10\x02\x62\x06proto3')
)

_CALCTYPE = _descriptor.EnumDescriptor(
  name='CalcType',
  full_name='ts_messaging.CalcType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATEKEYSHARE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LITTLEK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALPHA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=87,
)
_sym_db.RegisterEnumDescriptor(_CALCTYPE)

CalcType = enum_type_wrapper.EnumTypeWrapper(_CALCTYPE)
PRIVATEKEYSHARE = 0
LITTLEK = 1
ALPHA = 2


DESCRIPTOR.enum_types_by_name['CalcType'] = _CALCTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
