# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ts_messages_pb2 as ts__messages__pb2


class TSServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CallRegister = channel.unary_unary(
        '/ts_messaging.TSService/CallRegister',
        request_serializer=ts__messages__pb2.RegisterRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallCreateGroup = channel.unary_unary(
        '/ts_messaging.TSService/CallCreateGroup',
        request_serializer=ts__messages__pb2.CreateGroupRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.IdentityMessage.FromString,
        )
    self.CallInvite = channel.unary_unary(
        '/ts_messaging.TSService/CallInvite',
        request_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
        response_deserializer=ts__messages__pb2.InviteReply.FromString,
        )
    self.CallGroupIsSet = channel.unary_unary(
        '/ts_messaging.TSService/CallGroupIsSet',
        request_serializer=ts__messages__pb2.GroupIsSetRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallSharePublicKey = channel.unary_unary(
        '/ts_messaging.TSService/CallSharePublicKey',
        request_serializer=ts__messages__pb2.SharePublicKeyRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallRequestData = channel.unary_unary(
        '/ts_messaging.TSService/CallRequestData',
        request_serializer=ts__messages__pb2.DataRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.DataReply.FromString,
        )
    self.CallCreateSecret = channel.unary_unary(
        '/ts_messaging.TSService/CallCreateSecret',
        request_serializer=ts__messages__pb2.CreateSecretRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.IdentityMessage.FromString,
        )
    self.CallGroupIsVerified = channel.unary_unary(
        '/ts_messaging.TSService/CallGroupIsVerified',
        request_serializer=ts__messages__pb2.GroupIsVerifiedRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallInitiatePresign = channel.unary_unary(
        '/ts_messaging.TSService/CallInitiatePresign',
        request_serializer=ts__messages__pb2.InitPresignReqRep.SerializeToString,
        response_deserializer=ts__messages__pb2.InitPresignReqRep.FromString,
        )
    self.CallPresigning = channel.unary_unary(
        '/ts_messaging.TSService/CallPresigning',
        request_serializer=ts__messages__pb2.SharePublicKeyRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallCollateVWData = channel.unary_unary(
        '/ts_messaging.TSService/CallCollateVWData',
        request_serializer=ts__messages__pb2.CollateVWDataRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallSharedVWData = channel.unary_unary(
        '/ts_messaging.TSService/CallSharedVWData',
        request_serializer=ts__messages__pb2.SharedVWDataRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallEphemKeyComplete = channel.unary_unary(
        '/ts_messaging.TSService/CallEphemKeyComplete',
        request_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallPubKeyComplete = channel.unary_unary(
        '/ts_messaging.TSService/CallPubKeyComplete',
        request_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallPresignComplete = channel.unary_unary(
        '/ts_messaging.TSService/CallPresignComplete',
        request_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallCompleted = channel.unary_unary(
        '/ts_messaging.TSService/CallCompleted',
        request_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallReadyToSign = channel.unary_unary(
        '/ts_messaging.TSService/CallReadyToSign',
        request_serializer=ts__messages__pb2.ReadyToSignRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.IdentityMessage.FromString,
        )
    self.CallSign = channel.unary_unary(
        '/ts_messaging.TSService/CallSign',
        request_serializer=ts__messages__pb2.SignRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.GenericReply.FromString,
        )
    self.CallRequestSignature = channel.unary_unary(
        '/ts_messaging.TSService/CallRequestSignature',
        request_serializer=ts__messages__pb2.SignatureRequest.SerializeToString,
        response_deserializer=ts__messages__pb2.SignatureReply.FromString,
        )


class TSServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CallRegister(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallCreateGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallInvite(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallGroupIsSet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallSharePublicKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallRequestData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallCreateSecret(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallGroupIsVerified(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallInitiatePresign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallPresigning(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallCollateVWData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallSharedVWData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallEphemKeyComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallPubKeyComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallPresignComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallCompleted(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallReadyToSign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallSign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallRequestSignature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TSServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CallRegister': grpc.unary_unary_rpc_method_handler(
          servicer.CallRegister,
          request_deserializer=ts__messages__pb2.RegisterRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallCreateGroup': grpc.unary_unary_rpc_method_handler(
          servicer.CallCreateGroup,
          request_deserializer=ts__messages__pb2.CreateGroupRequest.FromString,
          response_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
      ),
      'CallInvite': grpc.unary_unary_rpc_method_handler(
          servicer.CallInvite,
          request_deserializer=ts__messages__pb2.IdentityMessage.FromString,
          response_serializer=ts__messages__pb2.InviteReply.SerializeToString,
      ),
      'CallGroupIsSet': grpc.unary_unary_rpc_method_handler(
          servicer.CallGroupIsSet,
          request_deserializer=ts__messages__pb2.GroupIsSetRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallSharePublicKey': grpc.unary_unary_rpc_method_handler(
          servicer.CallSharePublicKey,
          request_deserializer=ts__messages__pb2.SharePublicKeyRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallRequestData': grpc.unary_unary_rpc_method_handler(
          servicer.CallRequestData,
          request_deserializer=ts__messages__pb2.DataRequest.FromString,
          response_serializer=ts__messages__pb2.DataReply.SerializeToString,
      ),
      'CallCreateSecret': grpc.unary_unary_rpc_method_handler(
          servicer.CallCreateSecret,
          request_deserializer=ts__messages__pb2.CreateSecretRequest.FromString,
          response_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
      ),
      'CallGroupIsVerified': grpc.unary_unary_rpc_method_handler(
          servicer.CallGroupIsVerified,
          request_deserializer=ts__messages__pb2.GroupIsVerifiedRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallInitiatePresign': grpc.unary_unary_rpc_method_handler(
          servicer.CallInitiatePresign,
          request_deserializer=ts__messages__pb2.InitPresignReqRep.FromString,
          response_serializer=ts__messages__pb2.InitPresignReqRep.SerializeToString,
      ),
      'CallPresigning': grpc.unary_unary_rpc_method_handler(
          servicer.CallPresigning,
          request_deserializer=ts__messages__pb2.SharePublicKeyRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallCollateVWData': grpc.unary_unary_rpc_method_handler(
          servicer.CallCollateVWData,
          request_deserializer=ts__messages__pb2.CollateVWDataRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallSharedVWData': grpc.unary_unary_rpc_method_handler(
          servicer.CallSharedVWData,
          request_deserializer=ts__messages__pb2.SharedVWDataRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallEphemKeyComplete': grpc.unary_unary_rpc_method_handler(
          servicer.CallEphemKeyComplete,
          request_deserializer=ts__messages__pb2.IdentityMessage.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallPubKeyComplete': grpc.unary_unary_rpc_method_handler(
          servicer.CallPubKeyComplete,
          request_deserializer=ts__messages__pb2.IdentityMessage.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallPresignComplete': grpc.unary_unary_rpc_method_handler(
          servicer.CallPresignComplete,
          request_deserializer=ts__messages__pb2.IdentityMessage.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallCompleted': grpc.unary_unary_rpc_method_handler(
          servicer.CallCompleted,
          request_deserializer=ts__messages__pb2.IdentityMessage.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallReadyToSign': grpc.unary_unary_rpc_method_handler(
          servicer.CallReadyToSign,
          request_deserializer=ts__messages__pb2.ReadyToSignRequest.FromString,
          response_serializer=ts__messages__pb2.IdentityMessage.SerializeToString,
      ),
      'CallSign': grpc.unary_unary_rpc_method_handler(
          servicer.CallSign,
          request_deserializer=ts__messages__pb2.SignRequest.FromString,
          response_serializer=ts__messages__pb2.GenericReply.SerializeToString,
      ),
      'CallRequestSignature': grpc.unary_unary_rpc_method_handler(
          servicer.CallRequestSignature,
          request_deserializer=ts__messages__pb2.SignatureRequest.FromString,
          response_serializer=ts__messages__pb2.SignatureReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ts_messaging.TSService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
